### ISSUE TITLE
Marble TO-DO

### ISSUE THREAD

**Issue by SkyLightQP** [SkyLightQP/marble#33]
## TO-DO

- [ ]  메인페이지 (랜딩페이지)
- [x]  토큰 자동 갱신
- [x]  방 만들기
- [x]  방 접속
- [x]  방 퇴장
- [ ]  방 설정 수정
- [x]  플레이어 리스트
- [x]  현재 자산
- [x]  현재 랭킹
- [x]  주사위 굴리기
- [x]  땅 사기
    - [x]  건물(집, 빌딩, 호텔) 사기
    - [x]  땅 또는 건물을 샀을 때 UI
- [x]  벌금 내기
- [x] 게임 중퇴 처리
    - [x] 게임페이지에서 중퇴하면 플레이어 리스트에서도 삭제해야 함
    - [x]  중퇴 시 다음 순서 플레이어에게 주사위 권한이 넘어가야 함
- [x]  Zustand 적용
- [x]  플레이어가 액션이 끝날 때 다음 턴으로 넘어가야 함
    - [x]  액션 모달이 닫히면 턴 종료 신호를 보내야 함
    - [ ]  액션 모달 열린 뒤 일정 시간이 지나면 자동으로 턴을 끝내야 됨
- [x]  게임보드에 모든 플레이어의 땅, 건물을 표시해야 함
- [x]  아무 액션을 안했어도 턴이 넘어가야 함
    - [x]  SpecialCard 일 때도 턴이 넘어가야 함
    - [x]  내 도시에 왔을 때도 턴이 넘어가야 함
- [ ] 남은 플레이어(파산한 플레이어 제외)가 1명이면 게임을 종료해야 함
- [ ] 채팅
- [ ] 게임 종료
